---
title: Max Levin
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  subpages:
    title: subpages
    output: true
    permalink: "/pages/:name/"
sass:
  style: compressed
