---
title: Max Levin
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  subpages:
    title: Subpages
    output: true
    permalink: "/pages/:name/"
    images: true
default:
  - scope:
      path: ""
      type: "subpages"
    values:
      layout: "subpage"
      image: []
sass:
  style: compressed
