---
title: Max Levin
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  subpages:
    title: Subpages
    output: true
    permalink: "/pages/:name/"
    images: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: subpages
  values:
    layout: subpage
    images: []
sass:
  style: compressed
