---
title: Max Levin
timezone: America/New_York
collections:
  subpages:
    title: subpages
    permalink: /pages/:name/
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
sass:
  style: compressed
